services:
  garmin-activities:
    extends:
      file: docker-compose.yaml
      service: garmin-activities
    build:
      target: development
    image: garmin-activities-test
    container_name: garmin-activities-test
    command: npm run test
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
